### ISSUE TITLE
MOI Constraint Error

### ISSUE THREAD

**Issue by djsambor** [JuliaOpt/JuMP.jl#2024]
First time posting, been racking my brain for two days and can't find any open issues on this. Had a model that worked a few days ago and now the same model doesn't with no new changes, seems like a bug with Julia because it's a real simple issue or different package versions. It doesn't like when I set `@variable(m, x >=0)` but it does okay with `@variable(m, x)`. But with this I can't set `@variable(m, x, Bin)` like I used to. Here's the error: 
```
ERROR: LoadError: MethodError: MathOptInterface.supports_constraint(::JuMP._MOIModel{Float64}, ::Type{MathOptInterface.SingleVariable}, ::Type{MathOptInterface.GreaterThan{Float64}}) is ambiguous. Candidates:
  supports_constraint(model::JuMP._MOIModel{#251#T}, ::Type{#s129} where #s129<:Union{SingleVariable, ScalarAffineFunction{#251#T}, ScalarQuadraticFunction{#251#T}}, ::Type{#s128} where #s128<:Union{Integer, ZeroOne, EqualTo{#251#T}, GreaterThan{#251#T}, Interval{#251#T}, LessThan{#251#T}}) where #251#T in JuMP at ~/.julia/packages/MathOptInterface/mvlGI/src/Utilities/model.jl:997
  supports_constraint(::MathOptInterface.Utilities.AbstractModel{T}, ::Type{MathOptInterface.SingleVariable}, ::Type{#s176} where #s176<:Union{Integer, ZeroOne, EqualTo{T}, GreaterThan{T}, Interval{T}, LessThan{T}}) where T in MathOptInterface.Utilities at ~/.julia/packages/MathOptInterface/mvlGI/src/Utilities/model.jl:469
Possible fix, define
  supports_constraint(::JuMP._MOIModel{T}, ::Type{MathOptInterface.SingleVariable}, ::Type{#s176} where #s176<:Union{Integer, ZeroOne, EqualTo{T}, GreaterThan{T}, Interval{T}, LessThan{T}})
Stacktrace:
 [1] add_constraint(::MathOptInterface.Utilities.UniversalFallback{JuMP._MOIModel{Float64}}, ::MathOptInterface.SingleVariable, ::MathOptInterface.GreaterThan{Float64}) at ~/.julia/packages/MathOptInterface/mvlGI/src/Utilities/universalfallback.jl:357
 [2] add_constraint(::MathOptInterface.Utilities.CachingOptimizer{MathOptInterface.AbstractOptimizer,MathOptInterface.Utilities.UniversalFallback{JuMP._MOIModel{Float64}}}, ::MathOptInterface.SingleVariable, ::MathOptInterface.GreaterThan{Float64}) at /Users/danielsambor/.julia/packages/MathOptInterface/mvlGI/src/Utilities/cachingoptimizer.jl:254
 [3] set_lower_bound(::VariableRef, ::Int64) at ~/.julia/packages/JuMP/jnmGG/src/variables.jl:358
 [4] add_variable(::Model, ::ScalarVariable{Int64,Float64,Float64,Float64}, ::String) at ~/.julia/packages/JuMP/jnmGG/src/variables.jl:745
 [5] top-level scope at ~/.julia/packages/JuMP/jnmGG/src/macros.jl:300
 [6] include at ./boot.jl:326 [inlined]
 [7] include_relative(::Module, ::String) at ./loading.jl:1038
 [8] include(::Module, ::String) at ./sysimg.jl:29
 [9] include(::String) at ./client.jl:403
 [10] top-level scope at none:0
```

**Comment by blegat** [comment]
It seems you are using JuMP v0.18 with MOI v0.9 which are incompatible.
You get this error when you give `SingleVariable` to the `MOI.Utilities.@model` macro should should not be done anymor with MOI v0.9.

**Comment by djsambor** [comment]
I tried updating JuMP but it still doesn't work. How do I fix this?

**Comment by blegat** [comment]
Either downgrade MOI to v0.8 or use this PR of JuMP: https://github.com/JuliaOpt/JuMP.jl/pull/2003

**Comment by odow** [comment]
> It seems you are using JuMP v0.18

You mean 0.19?

@djsambor what is the output of 
```Julia
] st
```

**Comment by djsambor** [comment]
Yes I was confused to because I have v0.19 jump and MOI v0.9 ... how do I get them to be compatible if they aren't already? 

 JuMP v0.19.0
  Juno v0.7.0
MathOptInterface v0.9.0

**Comment by odow** [comment]
Try
```Julia
rm MathOptInterface
```
Did you need to install it for a particular reason?

**Comment by blegat** [comment]
> You mean 0.19?

Indeed, thanks, I have corrected the earlier post

**Comment by djsambor** [comment]
@odow thanks but I tried that and I'm still getting the same problem. I didn't need to install it for any reason. I changed absolutely nothing and all of a sudden got this problem. Only thing I can think of is that I updated my Atom text editor but that shouldn't matter. Here's my st output: 

(v1.1) pkg> st
    Status `~/.julia/environments/v1.1/Project.toml`
  [7c4d4715] AmplNLWriter v0.5.0
  [c52e3926] Atom v0.9.1
  [336ed68f] CSV v0.5.11
  [9961bab8] Cbc v0.6.3
  [e2554f3b] Clp v0.6.2
  [a93c6f00] DataFrames v0.19.2
  [2e9cd046] Gurobi v0.6.0
  [b6b21f68] Ipopt v0.5.4
  [4076af6c] JuMP v0.19.2
  [e5e0dc1b] Juno v0.7.2
  [e5751d75] NPFinancial v0.0.0 [`~/.julia/dev/NPFinancial`]
  [438e738f] PyCall v1.91.2

**Comment by odow** [comment]
You may need to close Atom and re-open (or at least kill the Julia terminal and restart).

**Comment by djsambor** [comment]
Thanks ah of course that did it!
