### ISSUE TITLE
Problem with JuMP and Mosek

### ISSUE THREAD

**Issue by nxtruong** [JuliaOpt/JuMP.jl#773]
I am using JuMP 0.13 to solve a control problem (converted from Matlab). Because the optimization model needs to be repeated solved with different parameters, I make use of the fixed variables and change of objective function. The Julia code and supporting data file are here: https://www.dropbox.com/sh/13oo97ve7h7f4v0/AABeJiFgKw9M_2krcGLqWtFna?dl=0. It requires Mosek (I hope you have a license for Mosek), and MATLAB. The problem below doesn't happen with a simpler example that I tried.

The model seems to be solved correctly the first time (compared to Matlab's version). However, from the second time and on, it always gives incorrect answers (U is always -delta). Setting values of U to NaN didn't help. Only by resetting the solver (which I think will reset the internal model) we can get the correct answer the next time.

This problem didn't happen with Gurobi; it always gave the same answer every time. I couldn't use other solvers like SCS or ECOS because JuMP complained that these solvers didn't support quadratic objectives.

**Comment by mlubin** [comment]
Thanks for the report, this sounds like a potential bug in the Mosek interface (CC @ulfworsoe). Is resetting the solver a sufficient workaround for your purposes?

To use SCS or ECOS through JuMP you need to manually reformulate your problem as a second-order cone problem, which is not always the most natural input format.

**Comment by nxtruong** [comment]
Resetting the solver will slow down my controller. For now I'm using Gurobi, but of course I also want to use Mosek if possible.

**Comment by mlubin** [comment]
> Resetting the solver will slow down my controller.

Have you measured the actual impact of this? It may not be as large as you expect.

**Comment by nxtruong** [comment]
You are right. Resetting the solver seems to add only slightly to the total time.

While testing this, I observed that Gurobi took consistently similar amount of time to solve (1.38-1.4 seconds), while Mosek took a very wide, inconsistent range of duration from 0.9s to over 4s. Seems very strange and suspicious to me.

**Comment by ulfworsoe** [comment]
I will take a look at this.

**Comment by ulfworsoe** [comment]
The problem was in Mosek.jl, and I believe I have fixed this in the head revision. Could you checkout the master branch of Mosek.jl and verify that this solves the issue?

**Comment by nxtruong** [comment]
I checked out the master branch using `Pkg.checkout("Mosek")`. `Pkg.status()` showed for Mosek:

> Mosek           0.3.0+    master

However, the bug persisted. I restarted Julia but it's still there.

**Comment by ulfworsoe** [comment]
The build error has been fixed now. You should do ``Pkg.checkout("Mosek","master")``. I have added tests in ``MathProgBase.jl`` for the specific issue you demonstrated, so it should be solved in the latest revision.

**Comment by mlubin** [comment]
@nxtruong, please reopen this issue if it hasn't been resolved in the master branch of Mosek.jl
